### ISSUE TITLE
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setups'

### ISSUE THREAD

**Issue by wonx** [pawkakol1/worlds-air-quality-index#40]
Hi.

I noticed that worlds-air-quality-index for homeassistant stopped working for my locations. I'm using version 1.01, and now I get this error:

```
Error setting up entry New York (Upper East Side) for worlds_air_quality_index
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/worlds_air_quality_index/__init__.py", line 30, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setups'
```

I don't know how to troubleshoot it. I tried redownloading the integration, and disable/enable it, but that didn´t make any change.

**Comment by wonx** [comment]
Ok, the issue seems to have resolved itself by updating to the lastest version of homeassistant. In the May 2022 version it was failing.
