### ISSUE TITLE
TypeError in waqi_api.py prevents entity update

### ISSUE THREAD

**Issue by LinusHoppe** [pawkakol1/worlds-air-quality-index#6]
**Environment:**

- Home Assistant core-2022.5.5 and core-2022.6.0 (just upgraded without any effect)
- Python 3.9.9
- Supervisor supervisor-2022.05.3
- Home Assistant OS 8.1

**behavior:**

- After setting up one device / WAQI sensor, everything works fine
- After some time, the sensor does not update any more:
![02-06-_2022_07-04-11](https://user-images.githubusercontent.com/32911160/171556944-1222bbc5-066a-4e9c-a86d-8257c394491b.png)

**Log:**
```
Logger: homeassistant.components.sensor
Source: custom_components/worlds_air_quality_index/waqi_api.py:27
Integration: Sensor (documentation, issues)
First occurred: 06:54:27 (1 occurrences)
Last logged: 06:54:27

Error while setting up worlds_air_quality_index platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/worlds_air_quality_index/sensor.py", line 86, in async_setup_entry
    await hass.async_add_executor_job(requester.update)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 192, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/worlds_air_quality_index/waqi_api.py", line 27, in update
    self._stationName = self._data["data"]["city"]["name"]
TypeError: string indices must be integers
```

**Comment by pawkakol1** [comment]
Release v0.3.0
